#!/usr/bin/env php
<?php

$conf = __DIR__ . '/pinba.conf.php';
if (!file_exists($conf)) {
    throw new \RuntimeException(sprintf('Not found config file %s', $conf));
}

$conf = require $conf;

if (count($argv) < 2) {
    throw new \InvalidArgumentException('You must provide at least one argument');
}

if ('errors' == $argv[1]) {
    if (!isset($argv[2])) {
        throw new \InvalidArgumentException('You must provide `server_name` in the second argument');
    }

    $c = new \PDO($conf['dsn'], $conf['db_user'], $conf['db_pass']);

    $sql = 'SELECT count(*) FROM request WHERE status >= 500 AND server_name = :server_name';

    $s = $c->prepare($sql);
    $s->execute([ 'server_name' => $argv[2] ]);

    echo $s->fetchColumn();
} elseif ('discovery' == $argv[1]) {

    $c = new \PDO($conf['dsn'], $conf['db_user'], $conf['db_pass']);

    $sql = 'select distinct server_name from (select server_name, TIMESTAMPDIFF(HOUR, created_at ,NOW()) as ago from ipm_report_by_server_name having ago <= 24) t order by server_name;';

    $s = $c->prepare($sql);
    $s->execute();

    $result = [
        "data" => [],
    ];

    while ($name = $s->fetch()) {
        if(!in_array($name['server_name'], $conf['black_list_for_zabbix'])) {
            $result['data'][] = [ '{#SV_NAME}' => $name['server_name'] ];
        }
    }

    echo json_encode($result);
}

